@localUrl = http://localhost:3000
@renderUrl = https://publishapi-0h1y.onrender.com
@contactId = 6abc646bb7c0ac635aeb9004
@deleteId = REPLACE_WITH_ID_TO_DELETE

### Get all contacts locally
GET {{localUrl}}/contacts

### Get all contacts from Render
GET {{renderUrl}}/contacts

### Get one contact locally
GET {{localUrl}}/contacts/by-id?id={{contactId}}

### Get one contact from Render
GET {{renderUrl}}/contacts/by-id?id={{contactId}}

### Create a new contact locally
POST {{localUrl}}/contacts
Content-Type: application/json

{
  "firstName": "Jordan",
  "lastName": "Smith",
  "email": "jordan@example.com",
  "favoriteColor": "Blue",
  "birthday": "2002-08-20"
}

### Update a contact locally
PUT {{localUrl}}/contacts/{{contactId}}
Content-Type: application/json

{
  "firstName": "Maya",
  "lastName": "Rivera",
  "email": "maya.updated@example.com",
  "favoriteColor": "Green",
  "birthday": "2001-06-12"
}

### Delete a contact locally
DELETE {{localUrl}}/contacts/{{deleteId}}