@renderUrl = https://publishapi-0h1y.onrender.com

### Get all contacts from Render
GET {{renderUrl}}/contacts

### Get one contact
GET {{renderUrl}}/contacts/by-id?id=6ab716d21787ccacb387abb2

@localUrl = http://localhost:3000

### Create a new contact
POST {{localUrl}}/contacts
Content-Type: application/json

### Update one contact
PUT {{localUrl}}/contacts/6abc646bb7c0ac635aeb9004
Content-Type: application/json

### Delete duplicate contact
DELETE {{localUrl}}/contacts/6abc646bb7c0ac635aeb9004

{
  "firstName": "Maya",
  "lastName": "Rivera",
  "email": "maya.updated@example.com",
  "favoriteColor": "green",
  "birthday": "2001-06-12"
}
