@renderUrl = https://publishapi-0h1y.onrender.com

### Get all contacts from Render
GET {{renderUrl}}/contacts

### Get one contact
GET {{renderUrl}}/contacts/by-id?id=6abc646bb7c0ac635aeb9004

@localUrl = http://localhost:3000

### Create a new contact
POST {{localUrl}}/contacts
Content-Type: application/json

{
  "firstName": "Conner",
  "lastName": "Smith",
  "email": "csmith.updated@example.com",
  "favoriteColor": "green",
  "birthday": "2001-06-12"
}

### Update one contact
PUT {{localUrl}}/contacts/6ac122b0c3d900fbb031acbc
Content-Type: application/json


### Delete duplicate contact
DELETE {{localUrl}}/contacts/6ac122b0c3d900fbb031acbc


